### PR TITLE
Fixed the date format for expected attributes date_start & date_end, …

### PR DESCRIPTION
**Pull request by Skumring**
…should be in UTC time zone

### CODE REVIEW

**Comment by dmitry-sinina** [comment]
@gigorok could you explain idea of these changes?

**Comment by gigorok** [comment]
@dmitry-sinina the fixed specs before this changes always fail when you had been run it on machine under timezone different than UTC

**Comment by dmitry-sinina** [comment]
But reports should show data in application timezone. Could you add more details about your configuration and especially application output, like:
```
App Timezone Europe/Kiev
Yeti DB timezone UTC
CDR DB timezone UTC
ActiveRecord timezone utc
```

**Comment by gigorok** [comment]
only specs were fixed, reports data not changed. 

application timezone on CI & by default on local machine is UTC
but Time.parse without specifying of timezone as part of argument works differently (depends on machine timezone, CI - UTC, my local machine - Europe\Kiev)

so in this fixed specs we were comparing time in UTC with time in machine timezone (thats why specs were passed on CI but fail on local machines)

**Comment by dmitry-sinina** [comment]
I am asking because there are no issues on my local machine:
```$ bundle exec rspec spec/features/reports/custom_cdrs/new_custom_cdr_spec.rb 
[Coveralls] Using SimpleCov settings defined in block.
App Timezone Europe/Kiev
Yeti DB timezone UTC
CDR DB timezone UTC
ActiveRecord timezone utc
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}
NOTICE:  truncate cascades to table "contacts"
WARNING: Active Record does not support composite primary key.

cdr.cdr has composite primary key. Composite primary key is ignored.
WARNING: Active Record does not support composite primary key.

cdr.cdr has composite primary key. Composite primary key is ignored.
WARNING: Active Record does not support composite primary key.

cdr.cdr has composite primary key. Composite primary key is ignored.
WARNING: Active Record does not support composite primary key.

cdr.cdr has composite primary key. Composite primary key is ignored.
NOTICE:  truncate cascades to table "contacts"
.NOTICE:  truncate cascades to table "contacts"
.NOTICE:  truncate cascades to table "contacts"
.NOTICE:  truncate cascades to table "contacts"
.NOTICE:  truncate cascades to table "contacts"
.NOTICE:  truncate cascades to table "contacts"
.NOTICE:  truncate cascades to table "contacts"
.NOTICE:  truncate cascades to table "contacts"
.

Top 8 slowest examples (19.11 seconds, 98.8% of total time):
  Create new Custom Cdr without send_to creates record
    4.49 seconds ./spec/features/reports/custom_cdrs/new_custom_cdr_spec.rb:26
  Create new Custom Cdr with send_to shows flash notice
    2.54 seconds ./spec/support/examples/active_admin/shows_flash_message.rb:4
  Create new Custom Cdr with send_to changes records qty of Report::CustomCdr by 1
    2.19 seconds ./spec/support/examples/active_record/changes_records_qty_of.rb:4
  Create new Custom Cdr with send_to creates record and email log
    2.17 seconds ./spec/features/reports/custom_cdrs/new_custom_cdr_spec.rb:53
  Create new Custom Cdr with send_to changes records qty of Log::EmailLog by 1
    2.15 seconds ./spec/support/examples/active_record/changes_records_qty_of.rb:4
  Create new Custom Cdr without send_to shows flash notice
    1.93 seconds ./spec/support/examples/active_admin/shows_flash_message.rb:4
  Create new Custom Cdr without send_to changes records qty of Report::CustomCdr by 1
    1.84 seconds ./spec/support/examples/active_record/changes_records_qty_of.rb:4
  Create new Custom Cdr without send_to changes records qty of Log::EmailLog by 0
    1.81 seconds ./spec/support/examples/active_record/changes_records_qty_of.rb:4

Finished in 19.34 seconds (files took 2.65 seconds to load)
8 examples, 0 failures
```

**Comment by gigorok** [comment]
because you have `App Timezone Europe/Kiev`. I have - `UTC`. to respect application timezone in specs I suggest https://github.com/yeti-switch/yeti-web/pull/841

**Pull request merged**
