### PR TITLE
Allow json token request without csrf

### PR DESCRIPTION
**Pull request by thiadmer**
With recent csrf changes applied I could not request a token anymore for admin api access.
This worked in my case, any other suggestions are also appreciated. Copied from https://stackoverflow.com/a/34252150

### CODE REVIEW

**Comment by Fivell** [comment]
@thiadmer  thaks, can you try to switch  
```
config.action_controller.allow_forgery_protection = false
```

to 

```
config.action_controller.allow_forgery_protection = true
```

in 
config/environments/test.rb

**Comment by thiadmer** [comment]
@Fivell, I was running in dev mode. Adding `config.action_controller.allow_forgery_protection = false` to my development.rb fixed the issue.

```
curl -v --header "Content-Type: application/json" \
>   --request POST \
>   --data '{"auth":{"username":"admin","password":"111111"}}' \
>   http://localhost:3000/api/rest/admin/auth

< {"jwt":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTMwMzkxOTIsInN1YiI6M30.BZUIZsJzjg4-8WUyFxwJ6N-iCdEZQFzYi5Zjw6aXtGA"}
```

**Comment by thiadmer** [comment]
Enable allow forgery flag in test.rb breaks customer api auth tests, so applied same change there.

**Review by senid231 — CHANGES_REQUESTED** [review]
please replace `skip_before_action :verify_authenticity_token, raise: false` with  `protect_from_forgery with: :null_session` in `Api::RestController` too.

on failing test `spec/features/cdr/cdr_exports/delete_file_spec.rb` just add `js: true` metadata to describe and it will pass - it needed because on admin UI js code adds csrf token to link so we need this test to be running in headless chrome.

**Comment by senid231** [comment]
vulnerability will be solved in another PR

https://github.com/yeti-switch/yeti-web/pull/869

**Comment by Fivell** [comment]
> please replace `skip_before_action :verify_authenticity_token, raise: false` with `protect_from_forgery with: :null_session` in `Api::RestController` too.
> 
> on failing test `spec/features/cdr/cdr_exports/delete_file_spec.rb` just add `js: true` metadata to describe and it will pass - it needed because on admin UI js code adds csrf token to link so we need this test to be running in headless chrome.

@thiadmer can you do this last commit, please?

**Comment by Fivell** [comment]
@thiadmer thanks!

**Comment by thiadmer** [comment]
@Fivell thank you for your directions. Nice getting to know the project in more detail. Still learning now, but planning to contribute more later.

**Pull request merged**
