### PR TITLE
Autogenerate gateway and api accesses credentials

### PR DESCRIPTION
**Pull request by Skumring**
Fixes https://github.com/yeti-switch/yeti-web/issues/828

### CODE REVIEW

**Comment by dmitry-sinina** [comment]
would not be better to implement it on browser side, on js?

**Comment by dmitry-sinina** [comment]
also looks like current implementation will fill **incoming_auth_username/password** with random data on every gw creation. It is not ok because it will force customer to create gateways with username/password when this parameter is optional.

**Comment by Skumring** [comment]
@dmitry-sinina implemented generator via JS and used it for Gateway forms - will generate the new credentials by the double click on the input field (added hints below input fields).
new_credential_form_credential_generator

**Comment by Skumring** [comment]
From now generator running only manually by the click on the link in a hint of the input field.
new_gateway_form
new_api_accesses_form

**Pull request merged**
